### ISSUE TITLE
个人 CSS 预设

### ISSUE THREAD

**Issue by mrcaidev** [mrcaidev/blogs#6]
结合 [Tailwind CSS](https://tailwindcss.com/docs/preflight) 和 [Josh W Comeau](https://www.joshwcomeau.com/css/custom-css-reset) 的预设，修正了 CSS 一些默认的奇怪标准，让网页的初始样式更加符合现代化网页的设计标准。

```css
*,
*::before,
*::after {
  box-sizing: border-box;
  border-width: 0;
  border-style: solid;
}

*::before,
*::after {
  content: "";
}

* {
  margin: 0;
  padding: 0;
}

html {
  height: 100%;
}

body {
  height: 100%;
  line-height: 1.5;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen,
    Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", sans-serif;
  -webkit-font-smoothing: antialiased;
}

#root,
#__next {
  height: 100%;
  isolation: isolate;
}

img,
svg,
picture,
canvas,
video,
audio,
iframe,
embed,
object {
  display: block;
  max-width: 100%;
}

input,
button,
textarea,
select {
  font: inherit;
}

p,
h1,
h2,
h3,
h4,
h5,
h6 {
  overflow-wrap: break-word;
}

ol,
ul {
  list-style: none;
}

a {
  color: inherit;
  text-decoration: none;
}
```
